
<div class="container ">
<a href="./">
  <img src="imagens/logo.png" class="mx-auto d-block">
  </a>
    </div>
  
<div class="container">

<div class="row justify-content-center align-items-center">
    <h1>Acesso Restrito</h1>    
  </div>
  <hr/>
<div class="row justify-content-center align-items-center">
    <div class="col-lg-5">

    <?php 
            if($this->view->erroLogin == true){
       
                ?>
 
             <div class="alert alert-danger" role="alert">
           Falha no processo de login. Tente novamente.
         </div>
         <?php  } ?>
      <form method="post" action="/login">
      <div class="form-group">
      <label for="email">E-mail</label>
      <input type="email" class="form-control" id="email" name="email" placeholder="email@exemplo.com.br" required>
    </div>
      <div class="form-group">     
      <label for="senha">Senha</label>
      <input type="password" class="form-control" id="senha" name="senha" placeholder="senha" required>

      </div>
      <div class="form-group">

            <div class="row">
            <div class="col-sm-7">
              <div class="col"><button class="col-10 btn btn-secondary btn-sm float-left">Recuperar Senha</button></div>
            </div>
            <div class="col-sm-5">
              <div class="col"><button class="col-10 btn btn-success btn-sm float-right">Entrar</button></div>
            </div>
          </div>
        </div>
    </form>
    </div>  <!-- fim div col col-sm-->
  </div> <!-- fim div row justify-->
</div> 
