<div class="container">

<div>
    <img src="/imagens/logo.png"/>
    
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
    <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">Home</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="/painel/condominios">Condomínios</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="#">Pendências</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="pagamentos.php">Pagamentos</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Condôminos
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Condôminos</a>
          <a class="dropdown-item" href="#">Contratos</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="usuarios.php">Usuários</a>
        </div>
      </li>

    </ul>



    <span class="navbar-text">
    Seja bem vindo <?php echo($_SESSION['nome']); ?>.
      <a href="/logout">Logoff</a>

  </div>
  </nav>
       </div>


</div>



<div class="container">
  <div class="row">

    <div class="col">
    <table class="table">
  <thead class="thead-dark">


    <tr>
      <th scope="col">ID</th>
      <th scope="col">Nome</th>
      <th scope="col">Endereço</th>
      <th scope="col">Ação</th>
    </tr>
  </thead>
  <tbody>
  <?php 

foreach($this->view->dados as $cond_id => $valor){

?>
    <tr>
      <th scope="row"><?=$cond_id?> </th>
      <td><?=$valor['nome']?> </td>
      <td><?=$valor['endereco']?> </td>
      <td><a href="">Editar</a> | <a href="">Ver Apts</a> | <a href="">Ver Condôminos</a></td>
    </tr>
    <?php
}

?>

  </tbody>
</table>


    </div>

  </div>
</div>

